version: "3.7"
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    environment:
      TZ: "Asia/Bangkok"

networks:
  backend:
    external:
      name: backend
