version: "3.7"
services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - backend
    restart: always
    environment:
      INFLUXDB_DB: "db0" 
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "home2021"
      INFLUXDB_USER: "homeassistant"
      INFLUXDB_USER_PASSWORD: "home2021"
      TZ: "Asia/Bangkok"

  grafana:
    container_name: grafana
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - influxdb
    networks:
      - backend
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      GF_SERVER_ROOT_URL: "https://graph.your-domain.com"
      GF_SECURITY_ADMIN_PASSWORD: "secret1234"
    
  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb:/etc/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: home2021
      MYSQL_DATABASE: ha
      MYSQL_USER: ha
      MYSQL_PASSWORD: home2021
      TZ: "Asia/Bangkok"

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    environment:
      PMA_ABSOLUTE_URI: https://pma.wizth.com
      MYSQL_ROOT_PASSWORD: home2021
      TZ: "Asia/Bangkok"
      PMA_HOST: mariadb

  chronograf:
    container_name: monitoring-chronograf
    image: chronograf
    volumes:
      - ./chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    links:
      - influxdb
    networks:
      - backend
    restart: unless-stopped
    environment:
      TZ: "Asia/Bangkok"



volumes:
  db_conf:
      driver: local

networks:
  backend:
    external:
      name: backend
